package com.tingo.dao.origin;

import com.tingo.dto.origin.FwBmxx;

public interface FwBmxxDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FW_BMXX
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String ksid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FW_BMXX
     *
     * @mbggenerated
     */
    int insert(FwBmxx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FW_BMXX
     *
     * @mbggenerated
     */
    int insertSelective(FwBmxx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FW_BMXX
     *
     * @mbggenerated
     */
    FwBmxx selectByPrimaryKey(String ksid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FW_BMXX
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FwBmxx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FW_BMXX
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FwBmxx record);
}