package com.tingo.dao.origin;

import com.tingo.dto.origin.FwOaLm;

public interface FwOaLmDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FW_OA_LM
     *
     * @mbggenerated
     */
    int insert(FwOaLm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FW_OA_LM
     *
     * @mbggenerated
     */
    int insertSelective(FwOaLm record);
}