package com.tingo.dao.origin;

import com.tingo.dto.origin.FwRyxx;

public interface FwRyxxDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FW_RYXX
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String zgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FW_RYXX
     *
     * @mbggenerated
     */
    int insert(FwRyxx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FW_RYXX
     *
     * @mbggenerated
     */
    int insertSelective(FwRyxx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FW_RYXX
     *
     * @mbggenerated
     */
    FwRyxx selectByPrimaryKey(String zgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FW_RYXX
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FwRyxx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FW_RYXX
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FwRyxx record);
}