package com.tingo.dao.origin;

import com.tingo.dto.origin.FwXtFj;

public interface FwXtFjDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FW_XT_FJ
     *
     * @mbggenerated
     */
    int insert(FwXtFj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FW_XT_FJ
     *
     * @mbggenerated
     */
    int insertSelective(FwXtFj record);
}