package com.tingo.dto.origin;

public class FwBmxx {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FW_BMXX.KSID
     *
     * @mbggenerated
     */
    private String ksid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FW_BMXX.KSDM
     *
     * @mbggenerated
     */
    private String ksdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FW_BMXX.KSMC
     *
     * @mbggenerated
     */
    private String ksmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FW_BMXX.SJID
     *
     * @mbggenerated
     */
    private String sjid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FW_BMXX.KSID
     *
     * @return the value of FW_BMXX.KSID
     *
     * @mbggenerated
     */
    public String getKsid() {
        return ksid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FW_BMXX.KSID
     *
     * @param ksid the value for FW_BMXX.KSID
     *
     * @mbggenerated
     */
    public void setKsid(String ksid) {
        this.ksid = ksid == null ? null : ksid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FW_BMXX.KSDM
     *
     * @return the value of FW_BMXX.KSDM
     *
     * @mbggenerated
     */
    public String getKsdm() {
        return ksdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FW_BMXX.KSDM
     *
     * @param ksdm the value for FW_BMXX.KSDM
     *
     * @mbggenerated
     */
    public void setKsdm(String ksdm) {
        this.ksdm = ksdm == null ? null : ksdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FW_BMXX.KSMC
     *
     * @return the value of FW_BMXX.KSMC
     *
     * @mbggenerated
     */
    public String getKsmc() {
        return ksmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FW_BMXX.KSMC
     *
     * @param ksmc the value for FW_BMXX.KSMC
     *
     * @mbggenerated
     */
    public void setKsmc(String ksmc) {
        this.ksmc = ksmc == null ? null : ksmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FW_BMXX.SJID
     *
     * @return the value of FW_BMXX.SJID
     *
     * @mbggenerated
     */
    public String getSjid() {
        return sjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FW_BMXX.SJID
     *
     * @param sjid the value for FW_BMXX.SJID
     *
     * @mbggenerated
     */
    public void setSjid(String sjid) {
        this.sjid = sjid == null ? null : sjid.trim();
    }
}