package com.tingo.dto.origin;

import java.util.Date;

public class FwOaNr {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FW_OA_NR.NRID
     *
     * @mbggenerated
     */
    private String nrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FW_OA_NR.NRBT
     *
     * @mbggenerated
     */
    private String nrbt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FW_OA_NR.LMID
     *
     * @mbggenerated
     */
    private String lmid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FW_OA_NR.SRRY
     *
     * @mbggenerated
     */
    private String srry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FW_OA_NR.FBRQ
     *
     * @mbggenerated
     */
    private Date fbrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FW_OA_NR.GQRQ
     *
     * @mbggenerated
     */
    private Date gqrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FW_OA_NR.SRSJ
     *
     * @mbggenerated
     */
    private Date srsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FW_OA_NR.SHRY
     *
     * @mbggenerated
     */
    private String shry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FW_OA_NR.FJDZ
     *
     * @mbggenerated
     */
    private String fjdz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FW_OA_NR.ZDJCS
     *
     * @mbggenerated
     */
    private Integer zdjcs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FW_OA_NR.ZDTS
     *
     * @mbggenerated
     */
    private Short zdts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FW_OA_NR.NR
     *
     * @mbggenerated
     */
    private byte[] nr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FW_OA_NR.NRID
     *
     * @return the value of FW_OA_NR.NRID
     *
     * @mbggenerated
     */
    public String getNrid() {
        return nrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FW_OA_NR.NRID
     *
     * @param nrid the value for FW_OA_NR.NRID
     *
     * @mbggenerated
     */
    public void setNrid(String nrid) {
        this.nrid = nrid == null ? null : nrid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FW_OA_NR.NRBT
     *
     * @return the value of FW_OA_NR.NRBT
     *
     * @mbggenerated
     */
    public String getNrbt() {
        return nrbt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FW_OA_NR.NRBT
     *
     * @param nrbt the value for FW_OA_NR.NRBT
     *
     * @mbggenerated
     */
    public void setNrbt(String nrbt) {
        this.nrbt = nrbt == null ? null : nrbt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FW_OA_NR.LMID
     *
     * @return the value of FW_OA_NR.LMID
     *
     * @mbggenerated
     */
    public String getLmid() {
        return lmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FW_OA_NR.LMID
     *
     * @param lmid the value for FW_OA_NR.LMID
     *
     * @mbggenerated
     */
    public void setLmid(String lmid) {
        this.lmid = lmid == null ? null : lmid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FW_OA_NR.SRRY
     *
     * @return the value of FW_OA_NR.SRRY
     *
     * @mbggenerated
     */
    public String getSrry() {
        return srry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FW_OA_NR.SRRY
     *
     * @param srry the value for FW_OA_NR.SRRY
     *
     * @mbggenerated
     */
    public void setSrry(String srry) {
        this.srry = srry == null ? null : srry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FW_OA_NR.FBRQ
     *
     * @return the value of FW_OA_NR.FBRQ
     *
     * @mbggenerated
     */
    public Date getFbrq() {
        return fbrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FW_OA_NR.FBRQ
     *
     * @param fbrq the value for FW_OA_NR.FBRQ
     *
     * @mbggenerated
     */
    public void setFbrq(Date fbrq) {
        this.fbrq = fbrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FW_OA_NR.GQRQ
     *
     * @return the value of FW_OA_NR.GQRQ
     *
     * @mbggenerated
     */
    public Date getGqrq() {
        return gqrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FW_OA_NR.GQRQ
     *
     * @param gqrq the value for FW_OA_NR.GQRQ
     *
     * @mbggenerated
     */
    public void setGqrq(Date gqrq) {
        this.gqrq = gqrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FW_OA_NR.SRSJ
     *
     * @return the value of FW_OA_NR.SRSJ
     *
     * @mbggenerated
     */
    public Date getSrsj() {
        return srsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FW_OA_NR.SRSJ
     *
     * @param srsj the value for FW_OA_NR.SRSJ
     *
     * @mbggenerated
     */
    public void setSrsj(Date srsj) {
        this.srsj = srsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FW_OA_NR.SHRY
     *
     * @return the value of FW_OA_NR.SHRY
     *
     * @mbggenerated
     */
    public String getShry() {
        return shry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FW_OA_NR.SHRY
     *
     * @param shry the value for FW_OA_NR.SHRY
     *
     * @mbggenerated
     */
    public void setShry(String shry) {
        this.shry = shry == null ? null : shry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FW_OA_NR.FJDZ
     *
     * @return the value of FW_OA_NR.FJDZ
     *
     * @mbggenerated
     */
    public String getFjdz() {
        return fjdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FW_OA_NR.FJDZ
     *
     * @param fjdz the value for FW_OA_NR.FJDZ
     *
     * @mbggenerated
     */
    public void setFjdz(String fjdz) {
        this.fjdz = fjdz == null ? null : fjdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FW_OA_NR.ZDJCS
     *
     * @return the value of FW_OA_NR.ZDJCS
     *
     * @mbggenerated
     */
    public Integer getZdjcs() {
        return zdjcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FW_OA_NR.ZDJCS
     *
     * @param zdjcs the value for FW_OA_NR.ZDJCS
     *
     * @mbggenerated
     */
    public void setZdjcs(Integer zdjcs) {
        this.zdjcs = zdjcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FW_OA_NR.ZDTS
     *
     * @return the value of FW_OA_NR.ZDTS
     *
     * @mbggenerated
     */
    public Short getZdts() {
        return zdts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FW_OA_NR.ZDTS
     *
     * @param zdts the value for FW_OA_NR.ZDTS
     *
     * @mbggenerated
     */
    public void setZdts(Short zdts) {
        this.zdts = zdts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FW_OA_NR.NR
     *
     * @return the value of FW_OA_NR.NR
     *
     * @mbggenerated
     */
    public byte[] getNr() {
        return nr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FW_OA_NR.NR
     *
     * @param nr the value for FW_OA_NR.NR
     *
     * @mbggenerated
     */
    public void setNr(byte[] nr) {
        this.nr = nr;
    }
}