package com.tingo.dto.origin;

public class FwOaLm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FW_OA_LM.LMID
     *
     * @mbggenerated
     */
    private String lmid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FW_OA_LM.LJ
     *
     * @mbggenerated
     */
    private String lj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FW_OA_LM.LMMC
     *
     * @mbggenerated
     */
    private String lmmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FW_OA_LM.FLLMID
     *
     * @mbggenerated
     */
    private String fllmid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FW_OA_LM.LMID
     *
     * @return the value of FW_OA_LM.LMID
     *
     * @mbggenerated
     */
    public String getLmid() {
        return lmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FW_OA_LM.LMID
     *
     * @param lmid the value for FW_OA_LM.LMID
     *
     * @mbggenerated
     */
    public void setLmid(String lmid) {
        this.lmid = lmid == null ? null : lmid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FW_OA_LM.LJ
     *
     * @return the value of FW_OA_LM.LJ
     *
     * @mbggenerated
     */
    public String getLj() {
        return lj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FW_OA_LM.LJ
     *
     * @param lj the value for FW_OA_LM.LJ
     *
     * @mbggenerated
     */
    public void setLj(String lj) {
        this.lj = lj == null ? null : lj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FW_OA_LM.LMMC
     *
     * @return the value of FW_OA_LM.LMMC
     *
     * @mbggenerated
     */
    public String getLmmc() {
        return lmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FW_OA_LM.LMMC
     *
     * @param lmmc the value for FW_OA_LM.LMMC
     *
     * @mbggenerated
     */
    public void setLmmc(String lmmc) {
        this.lmmc = lmmc == null ? null : lmmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FW_OA_LM.FLLMID
     *
     * @return the value of FW_OA_LM.FLLMID
     *
     * @mbggenerated
     */
    public String getFllmid() {
        return fllmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FW_OA_LM.FLLMID
     *
     * @param fllmid the value for FW_OA_LM.FLLMID
     *
     * @mbggenerated
     */
    public void setFllmid(String fllmid) {
        this.fllmid = fllmid == null ? null : fllmid.trim();
    }
}