package com.tingo.dto.origin;

public class FwRyxx {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FW_RYXX.ZGID
     *
     * @mbggenerated
     */
    private String zgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FW_RYXX.ZGGH
     *
     * @mbggenerated
     */
    private String zggh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FW_RYXX.XM
     *
     * @mbggenerated
     */
    private String xm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FW_RYXX.XB
     *
     * @mbggenerated
     */
    private String xb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FW_RYXX.SZKS
     *
     * @mbggenerated
     */
    private String szks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FW_RYXX.DLKL
     *
     * @mbggenerated
     */
    private String dlkl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FW_RYXX.ZGID
     *
     * @return the value of FW_RYXX.ZGID
     *
     * @mbggenerated
     */
    public String getZgid() {
        return zgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FW_RYXX.ZGID
     *
     * @param zgid the value for FW_RYXX.ZGID
     *
     * @mbggenerated
     */
    public void setZgid(String zgid) {
        this.zgid = zgid == null ? null : zgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FW_RYXX.ZGGH
     *
     * @return the value of FW_RYXX.ZGGH
     *
     * @mbggenerated
     */
    public String getZggh() {
        return zggh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FW_RYXX.ZGGH
     *
     * @param zggh the value for FW_RYXX.ZGGH
     *
     * @mbggenerated
     */
    public void setZggh(String zggh) {
        this.zggh = zggh == null ? null : zggh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FW_RYXX.XM
     *
     * @return the value of FW_RYXX.XM
     *
     * @mbggenerated
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FW_RYXX.XM
     *
     * @param xm the value for FW_RYXX.XM
     *
     * @mbggenerated
     */
    public void setXm(String xm) {
        this.xm = xm == null ? null : xm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FW_RYXX.XB
     *
     * @return the value of FW_RYXX.XB
     *
     * @mbggenerated
     */
    public String getXb() {
        return xb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FW_RYXX.XB
     *
     * @param xb the value for FW_RYXX.XB
     *
     * @mbggenerated
     */
    public void setXb(String xb) {
        this.xb = xb == null ? null : xb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FW_RYXX.SZKS
     *
     * @return the value of FW_RYXX.SZKS
     *
     * @mbggenerated
     */
    public String getSzks() {
        return szks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FW_RYXX.SZKS
     *
     * @param szks the value for FW_RYXX.SZKS
     *
     * @mbggenerated
     */
    public void setSzks(String szks) {
        this.szks = szks == null ? null : szks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FW_RYXX.DLKL
     *
     * @return the value of FW_RYXX.DLKL
     *
     * @mbggenerated
     */
    public String getDlkl() {
        return dlkl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FW_RYXX.DLKL
     *
     * @param dlkl the value for FW_RYXX.DLKL
     *
     * @mbggenerated
     */
    public void setDlkl(String dlkl) {
        this.dlkl = dlkl == null ? null : dlkl.trim();
    }
}