package com.tingo.dto.origin;

public class FwXtFj {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FW_XT_FJ.XH
     *
     * @mbggenerated
     */
    private String xh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FW_XT_FJ.ZJID
     *
     * @mbggenerated
     */
    private String zjid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FW_XT_FJ.FJLB
     *
     * @mbggenerated
     */
    private String fjlb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FW_XT_FJ.FJDX
     *
     * @mbggenerated
     */
    private Long fjdx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FW_XT_FJ.WJM1
     *
     * @mbggenerated
     */
    private String wjm1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FW_XT_FJ.WJM2
     *
     * @mbggenerated
     */
    private String wjm2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FW_XT_FJ.KZM
     *
     * @mbggenerated
     */
    private String kzm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FW_XT_FJ.XH
     *
     * @return the value of FW_XT_FJ.XH
     *
     * @mbggenerated
     */
    public String getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FW_XT_FJ.XH
     *
     * @param xh the value for FW_XT_FJ.XH
     *
     * @mbggenerated
     */
    public void setXh(String xh) {
        this.xh = xh == null ? null : xh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FW_XT_FJ.ZJID
     *
     * @return the value of FW_XT_FJ.ZJID
     *
     * @mbggenerated
     */
    public String getZjid() {
        return zjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FW_XT_FJ.ZJID
     *
     * @param zjid the value for FW_XT_FJ.ZJID
     *
     * @mbggenerated
     */
    public void setZjid(String zjid) {
        this.zjid = zjid == null ? null : zjid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FW_XT_FJ.FJLB
     *
     * @return the value of FW_XT_FJ.FJLB
     *
     * @mbggenerated
     */
    public String getFjlb() {
        return fjlb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FW_XT_FJ.FJLB
     *
     * @param fjlb the value for FW_XT_FJ.FJLB
     *
     * @mbggenerated
     */
    public void setFjlb(String fjlb) {
        this.fjlb = fjlb == null ? null : fjlb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FW_XT_FJ.FJDX
     *
     * @return the value of FW_XT_FJ.FJDX
     *
     * @mbggenerated
     */
    public Long getFjdx() {
        return fjdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FW_XT_FJ.FJDX
     *
     * @param fjdx the value for FW_XT_FJ.FJDX
     *
     * @mbggenerated
     */
    public void setFjdx(Long fjdx) {
        this.fjdx = fjdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FW_XT_FJ.WJM1
     *
     * @return the value of FW_XT_FJ.WJM1
     *
     * @mbggenerated
     */
    public String getWjm1() {
        return wjm1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FW_XT_FJ.WJM1
     *
     * @param wjm1 the value for FW_XT_FJ.WJM1
     *
     * @mbggenerated
     */
    public void setWjm1(String wjm1) {
        this.wjm1 = wjm1 == null ? null : wjm1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FW_XT_FJ.WJM2
     *
     * @return the value of FW_XT_FJ.WJM2
     *
     * @mbggenerated
     */
    public String getWjm2() {
        return wjm2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FW_XT_FJ.WJM2
     *
     * @param wjm2 the value for FW_XT_FJ.WJM2
     *
     * @mbggenerated
     */
    public void setWjm2(String wjm2) {
        this.wjm2 = wjm2 == null ? null : wjm2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FW_XT_FJ.KZM
     *
     * @return the value of FW_XT_FJ.KZM
     *
     * @mbggenerated
     */
    public String getKzm() {
        return kzm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FW_XT_FJ.KZM
     *
     * @param kzm the value for FW_XT_FJ.KZM
     *
     * @mbggenerated
     */
    public void setKzm(String kzm) {
        this.kzm = kzm == null ? null : kzm.trim();
    }
}